FROM node:16-alpine as build

WORKDIR /app
COPY ./typescript/simple-mercari-web /app

# ---
FROM fholzer/nginx-brotli:v1.12.2

WORKDIR /etc/nginx
ADD ./typescript/simple-mercari-web/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
