FROM golang:1.17-alpine

ENV PORT 8080
ENV GOPATH /go
ENV GO111MODULE on

RUN apk update && \
    apk add --no-cache sqlite && \
    apk add gcc musl-dev gcompat

RUN mkdir /go/src/db
RUN mkdir /go/src/go
WORKDIR /go/src/go

ADD db /go/src/db
ADD go /go/src/go

RUN go mod tidy

WORKDIR /go/src/go/app

RUN go build -o server

ENTRYPOINT [ "/go/src/go/app" ]
CMD ["/server"]