FROM golang:1.17-alpine

EXPOSE 80

ENV PORT 8080
ENV FRONT_URL=https://mercari-build-2022-frontend-dzpfucpr4q-an.a.run.app
ENV GOPATH /go
ENV GO111MODULE on

RUN apk update && \
    apk add --no-cache sqlite && \
    apk add gcc musl-dev gcompat

RUN mkdir /go/src/db
RUN mkdir /go/src/go
WORKDIR /go/src/go

ADD db /go/src/db
ADD go /go/src/go

RUN go mod tidy

WORKDIR /go/src/go/app

RUN go build -o server

CMD ["./server"]