name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  frontend-build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@master
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./typescript/simple-mercari-web

      - name: Build Development
        run: npm run build
        working-directory: ./typescript/simple-mercari-web

      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: build

  frontend-deploy-to-cloud-run:
    name: Deploy to Cloud Run
    needs: frontend-build
    runs-on: ubuntu-latest
    environment:
      name: Production
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: ./typescript/simple-mercari-web/.docker/build

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/381045458779/locations/global/workloadIdentityPools/mercari-listing/providers/gha-provider
          service_account: github-actions@build-mercari-2022-team6.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build a docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/mercari-build-2022-frontend:${{ github.sha }} . -f ./typescript/simple-mercari-web/.docker/dockerfile.production

      - name: Push the docker image to Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mercari-build-2022-frontend:${{ github.sha }}

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "mercari-build-2022-frontend" \
            --quiet \
            --region ${{ secrets.GCP_REGION }} \
            --image "gcr.io/${{ secrets.GCP_PROJECT_ID }}/mercari-build-2022-frontend:${{ github.sha }}" \
            --platform "managed" \
            --allow-unauthenticated \
            --quiet

  backennd-deploy-to-cloud-run:
    runs-on: ubuntu-latest
    environment:
      name: Production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/381045458779/locations/global/workloadIdentityPools/mercari-listing/providers/gha-provider
          service_account: github-actions@build-mercari-2022-team6.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} . -f ./go/dockerfile.production

      - name: Push the docker image to Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy mercari-build-2022-backend \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} \
              --port 8080 \
              --project ${{ secrets.GCP_PROJECT_ID }} \
              --region ${{ secrets.GCP_REGION }} \
              --platform=managed \
              --allow-unauthenticated \
              --quiet \
              --memory 4Gi \
              --cpu 4
